### ISSUE TITLE
Function 'apply' does not work with substr

### ISSUE THREAD

**Issue by dnebauer** [houseabsolute/List-SomeUtils#7]
This use of function `apply` does not work:
```perl
my @tranformed = apply { substr $_, 0, 4 } @orig;
```
although it does work with `map`. It's no big deal because... `map`, but clearly there are limitations to `apply` which are not described in the manpage.

**Comment by autarch** [comment]
Ah, I see the issue. The `apply` sub requires you to assign to `$_` to change the elements of the list. It's kind of weird and the docs don't make this entirely clear.

But what it does is make a copy of the input list and then use the sub passed to apply on each element in turn. Since the elements are passed as `$_`, any modifications to the variable are seen in the list copy, but not the original.

I will make some changes to the docs to try to make this clearer.

**Comment by autarch** [comment]
Fixed in 0.58.
